[package]
name = "axum-strangler"
version = "0.2.0"
edition = "2021"
license = "MIT OR Apache-2.0"
description = "Strangler fig pattern utility crate for the Axum framework"
readme = "README.md"
repository = "https://github.com/MidasLamb/axum-strangler"
homepage = "https://github.com/MidasLamb/axum-strangler"

[dependencies]
axum = "0.5.13"
hyper = { version = "0.14.20", features = ["client", "http2", "tcp"] }
reqwest = "0.11.11"
tower-service = "0.3.2"

[dev-dependencies]
reqwest = "0.11.11"
tokio = { version = "1.20.0", features = ["full"] }

