[package]
name = "axum-strangler"
version = "0.2.0"
edition = "2021"
license = "MIT OR Apache-2.0"
description = "Strangler fig pattern utility crate for the Axum framework"
readme = "README.md"
repository = "https://github.com/MidasLamb/axum-strangler"
homepage = "https://github.com/MidasLamb/axum-strangler"

[dependencies]
axum = { version = "0.5.13", features = ["ws"]}
hyper = { version = "0.14.20", features = ["client", "http2", "tcp"] }
reqwest = "0.11.11"
tower-service = "0.3.2"
tokio-tungstenite = "0.17.2"
tokio = { version = "1.20.0", features = ["full"] }
futures-util = "0.3.21"
tracing = "0.1.36"

[dev-dependencies]
reqwest = "0.11.11"
tracing-subscriber = { version = "0.3", features = ["env-filter"]}
