on:
  push:
    branches: [master]
  pull_request:
name: cargo test
jobs:
  test-all-features:
    runs-on: ubuntu-latest
    name: test all features
    steps:
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - uses: actions/checkout@v2
      - name: cargo install cargo-hack
        uses: actions-rs/cargo@v1
        with:
          command: install
          args: cargo-hack
      - name: cargo test
        uses: actions-rs/cargo@v1
        with:
          command: hack
          args: test --feature-powerset --group-features websocket-native-tls,websocket-rustls-tls-native-roots,websocket-rustls-tls-webpki-roots
