on:
  push:
    branches: [master]
  pull_request:
name: cargo test
jobs:
  test-all-features:
    runs-on: ubuntu-latest
    name: test all features
    steps:
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
      - uses: actions/checkout@v2
      - name: cargo install cargo-all-features
        uses: actions-rs/cargo@v1
        with:
          command: install
          args: cargo-all-features
      - name: cargo test-all-features
        uses: actions-rs/cargo@v1
        with:
          command: test-all-features
